### PR TITLE
Update to latest Zig

### LINKED ISSUE #2: Slimy fails to build on Zig 0.12.0
When trying to build slimy using `zig build`, at first it fails due to:
```
/mnt/Biblioteko/Gits/slimy/build.zig.zon:1:2: error: missing top-level 'paths' field
.{
 ^
```

This is simple enough to fix by just adding an empty paths specification to build.zig.zon as follows:
```
.{
    .name = "slimy",
    .version = "0.1.0-dev",
    .dependencies = .{
        .optz = .{
            .url = "https://github.com/silversquirl/optz/archive/a57f38365d85a8c1151171a7e3a715ed285e2a9d.tar.gz",
            .hash = "12200ddfa43ada90f0a56d8cd1664c91321001a30c1bbb5a6ac6d405161c4750d6d2",
        },
        .cpuinfo = .{
            .url = "https://github.com/silversquirl/cpuinfo-zig/archive/bf816de759cf02c95ee9d94e7e7ab3e373a7286f.tar.gz",
            .hash = "1220e168bbe411e4a92ffb194a7cf353997e69af530ca9ed4b4411c178948b340995",
        },
        .zcompute = .{
            .url = "https://github.com/silversquirl/zcompute/archive/60312ae55c6447a387462ab0212b7c163dfd50d3.tar.gz",
            .hash = "12206a1edb5a051dbdbdd106bdc19ac3f1f1237de076e80fb7325d5a98a98f8df54b",
        },
    },
    .paths = .{""},
}
```

What is a bit harder to fix, that I'm currently still working on, is that the dependencies are apparently out of date too. After fetching them, it errors out with the following:
```
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/build_integration.zig:171:22: error: expected 2 arguments, found 3
        const self = @fieldParentPtr(ShaderCompileStep, "step", step);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/build_integration.zig:77:22: error: expected 2 arguments, found 3
        const self = @fieldParentPtr(GenerateStep, "step", step);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/xml.zig:235:13: error: local variable is never mutated
        var end = mem.indexOfScalarPos(u8, self.source, self.offset, '\n') orelse self.source.len;
            ^~~
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/xml.zig:235:13: note: consider using 'const'
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:26:9: error: local variable is never mutated
    var reg = registry.Registry{
        ^~~
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:26:9: note: consider using 'const'
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:42:9: error: local variable is never mutated
    var commands_elem = root.findChildByTag("commands") orelse return error.InvalidRegistry;
        ^~~~~~~~~~~~~
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:42:9: note: consider using 'const'
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:41:9: error: local variable is never mutated
    var types_elem = root.findChildByTag("types") orelse return error.InvalidRegistry;
        ^~~~~~~~~~
/home/happysmash27/.cache/zig/p/1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea/generator/vulkan/parse.zig:41:9: note: consider using 'const'
/mnt/Biblioteko/Gits/Build/slimy/build.zig:5:21: error: root struct of file 'std' has no member named 'build'
pub fn build(b: *std.build.Builder) !void {
                 ~~~^~~~~~
/usr/lib64/zig/0.12.0/lib/std/std.zig:1:1: note: struct declared here
pub const ArrayHashMap = array_hash_map.ArrayHashMap;
^~~
referenced by:
    runBuild__anon_8992: /usr/lib64/zig/0.12.0/lib/std/Build.zig:2078:50
    main: /usr/lib64/zig/0.12.0/lib/compiler/build_runner.zig:300:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

`1220d3e1254af9c8fd4c3f09bd9f50f51dc5eaa5506f845ed67bcd75e1e2961ce1ea` appears to be some version of [vulkan-zig](https://github.com/Snektron/vulkan-zig/), and I have not yet figured out which specific dependency is pulling it.

I am guessing there will be other errors after I fix these ones, too, since the last update was for 0.11.0.

### PR DESCRIPTION
**Pull request by mlugg**
Tested on Zig 0.14.0-dev.367+a57479afc.

Only non-trivial migration point is that I made the `glslc` integration actually use the cache system correctly. The compiled SPIR-V shader is now exposed through a module `search_spv` which is used with `@embedFile("search_spv")`.

Resolves: #2

### CODE REVIEW

**Comment by silversquirl** [comment]
Could you update the CI to 0.13.0, as well as double checking this builds on that version?
